CONTENTS_FILE_jira_clone_client_src_shared_utils_api = \
    "aW1wb3J0IGF4aW9zIGZyb20gJ2F4aW9zJzsKCmltcG9ydCBoaXN0b3J5IGZyb20gJ2Jyb3d" \
    "zZXJIaXN0b3J5JzsKaW1wb3J0IHRvYXN0IGZyb20gJ3NoYXJlZC91dGlscy90b2FzdCc7Cm" \
    "ltcG9ydCB7IG9iamVjdFRvUXVlcnlTdHJpbmcgfSBmcm9tICdzaGFyZWQvdXRpbHMvdXJsJ" \
    "zsKaW1wb3J0IHsgZ2V0U3RvcmVkQXV0aFRva2VuLCByZW1vdmVTdG9yZWRBdXRoVG9rZW4g" \
    "fSBmcm9tICdzaGFyZWQvdXRpbHMvYXV0aFRva2VuJzsKCmNvbnN0IGRlZmF1bHRzID0gewo" \
    "gIGJhc2VVUkw6IHByb2Nlc3MuZW52LkFQSV9VUkwgfHwgJ2h0dHA6Ly9sb2NhbGhvc3Q6Mz" \
    "AwMCcsCiAgaGVhZGVyczogKCkgPT4gKHsKICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljY" \
    "XRpb24vanNvbicsCiAgICBBdXRob3JpemF0aW9uOiBnZXRTdG9yZWRBdXRoVG9rZW4oKSA/" \
    "IGBCZWFyZXIgJHtnZXRTdG9yZWRBdXRoVG9rZW4oKX1gIDogdW5kZWZpbmVkLAogIH0pLAo" \
    "gIGVycm9yOiB7CiAgICBjb2RlOiAnSU5URVJOQUxfRVJST1InLAogICAgbWVzc2FnZTogJ1" \
    "NvbWV0aGluZyB3ZW50IHdyb25nLiBQbGVhc2UgY2hlY2sgeW91ciBpbnRlcm5ldCBjb25uZ" \
    "WN0aW9uIG9yIGNvbnRhY3Qgb3VyIHN1cHBvcnQuJywKICAgIHN0YXR1czogNTAzLAogICAg" \
    "ZGF0YToge30sCiAgfSwKfTsKCmNvbnN0IGFwaSA9IChtZXRob2QsIHVybCwgdmFyaWFibGV" \
    "zKSA9PgogIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHsKICAgIGF4aW9zKH" \
    "sKICAgICAgdXJsOiBgJHtkZWZhdWx0cy5iYXNlVVJMfSR7dXJsfWAsCiAgICAgIG1ldGhvZ" \
    "CwKICAgICAgaGVhZGVyczogZGVmYXVsdHMuaGVhZGVycygpLAogICAgICBwYXJhbXM6IG1l" \
    "dGhvZCA9PT0gJ2dldCcgPyB2YXJpYWJsZXMgOiB1bmRlZmluZWQsCiAgICAgIGRhdGE6IG1" \
    "ldGhvZCAhPT0gJ2dldCcgPyB2YXJpYWJsZXMgOiB1bmRlZmluZWQsCiAgICAgIHBhcmFtc1" \
    "NlcmlhbGl6ZXI6IG9iamVjdFRvUXVlcnlTdHJpbmcsCiAgICB9KS50aGVuKAogICAgICByZ" \
    "XNwb25zZSA9PiB7CiAgICAgICAgcmVzb2x2ZShyZXNwb25zZS5kYXRhKTsKICAgICAgfSwK" \
    "ICAgICAgZXJyb3IgPT4gewogICAgICAgIGlmIChlcnJvci5yZXNwb25zZSkgewogICAgICA" \
    "gICAgaWYgKGVycm9yLnJlc3BvbnNlLmRhdGEuZXJyb3IuY29kZSA9PT0gJ0lOVkFMSURfVE" \
    "9LRU4nKSB7CiAgICAgICAgICAgIHJlbW92ZVN0b3JlZEF1dGhUb2tlbigpOwogICAgICAgI" \
    "CAgICBoaXN0b3J5LnB1c2goJy9hdXRoZW50aWNhdGUnKTsKICAgICAgICAgIH0gZWxzZSB7" \
    "CiAgICAgICAgICAgIHJlamVjdChlcnJvci5yZXNwb25zZS5kYXRhLmVycm9yKTsKICAgICA" \
    "gICAgIH0KICAgICAgICB9IGVsc2UgewogICAgICAgICAgcmVqZWN0KGRlZmF1bHRzLmVycm" \
    "9yKTsKICAgICAgICB9CiAgICAgIH0sCiAgICApOwogIH0pOwoKY29uc3Qgb3B0aW1pc3RpY" \
    "1VwZGF0ZSA9IGFzeW5jICh1cmwsIHsgdXBkYXRlZEZpZWxkcywgY3VycmVudEZpZWxkcywg" \
    "c2V0TG9jYWxEYXRhIH0pID0+IHsKICB0cnkgewogICAgc2V0TG9jYWxEYXRhKHVwZGF0ZWR" \
    "GaWVsZHMpOwogICAgYXdhaXQgYXBpKCdwdXQnLCB1cmwsIHVwZGF0ZWRGaWVsZHMpOwogIH" \
    "0gY2F0Y2ggKGVycm9yKSB7CiAgICBzZXRMb2NhbERhdGEoY3VycmVudEZpZWxkcyk7CiAgI" \
    "CB0b2FzdC5lcnJvcihlcnJvcik7CiAgfQp9OwoKZXhwb3J0IGRlZmF1bHQgewogIGdldDog" \
    "KC4uLmFyZ3MpID0+IGFwaSgnZ2V0JywgLi4uYXJncyksCiAgcG9zdDogKC4uLmFyZ3MpID0" \
    "+IGFwaSgncG9zdCcsIC4uLmFyZ3MpLAogIHB1dDogKC4uLmFyZ3MpID0+IGFwaSgncHV0Jy" \
    "wgLi4uYXJncyksCiAgcGF0Y2g6ICguLi5hcmdzKSA9PiBhcGkoJ3BhdGNoJywgLi4uYXJnc" \
    "yksCiAgZGVsZXRlOiAoLi4uYXJncykgPT4gYXBpKCdkZWxldGUnLCAuLi5hcmdzKSwKICBv" \
    "cHRpbWlzdGljVXBkYXRlLAp9Owo="

CONTENTS_FILE_jira_clone_client_src_shared_utils_authToken = \
    "ZXhwb3J0IGNvbnN0IGdldFN0b3JlZEF1dGhUb2tlbiA9ICgpID0+IGxvY2FsU3RvcmFnZS5" \
    "nZXRJdGVtKCdhdXRoVG9rZW4nKTsKCmV4cG9ydCBjb25zdCBzdG9yZUF1dGhUb2tlbiA9IH" \
    "Rva2VuID0+IGxvY2FsU3RvcmFnZS5zZXRJdGVtKCdhdXRoVG9rZW4nLCB0b2tlbik7Cgple" \
    "HBvcnQgY29uc3QgcmVtb3ZlU3RvcmVkQXV0aFRva2VuID0gKCkgPT4gbG9jYWxTdG9yYWdl" \
    "LnJlbW92ZUl0ZW0oJ2F1dGhUb2tlbicpOwo="
