version: "3.9"
services:
  database:
    image: mongo:latest
    container_name: cytee-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ThisPasswordIsNotSuperSecretAsItIsOnlyUsedInsideDocker
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: cytee-api
    container_name: cytee-api
    environment:
      - MONGO_SERVER=database
      - MONGO_PORT=27017
    volumes:
      - [EDIT-ME]:/mnt/host-share
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: cytee-client
    container_name: cytee-client
    ports:
      - "3000:80"