WEBSOCKET_STATUS_URL = "sock_choose_files"

WEBSOCKET_OK_BUSY_ANALYZE = "BUSY_ANALYZE"
WEBSOCKET_OK_BUSY_POST_PROCESS = "BUSY_POST_PROCESS"
WEBSOCKET_OK_DONE = "DONE"

WEBSOCKET_ERR_FILE_EMPTY = "ERR_FILE_EMPTY"
WEBSOCKET_ERR_FILE_MISSING = "ERR_FILE_MISSING"
WEBSOCKET_ERR_PARSE_FAILURE = "ERR_PARSE_FAILURE"
WEBSOCKET_ERR_UNEXPECTED = "ERR_UNEXPECTED"
